# --- General options --- #

url: "https://fawadmsee20.github.io"
baseurl: ""

title: Fawad Khan
description: AI Researcher | Wireless Power Transfer | Machine Learning | Energy Systems

# --- Navigation bar --- #

navbar-links:
  About Me: "aboutme"
  Research:
    - Interests: "researchinterest"
    - Publications: "publication"
    - Projects: "projects"
  Contact: "contactnew"

# Profile image
avatar: "/_data/fawad-new2.jpg"

# --- Design --- #

navbar-col: "#0f172a"
navbar-text-col: "#FFFFFF"
navbar-children-col: "#1d4ed8"
page-col: "#FFFFFF"
link-col: "#2563eb"
hover-col: "#1d4ed8"
footer-col: "#0f172a"
footer-text-col: "#FFFFFF"
footer-link-col: "#60a5fa"

footer-img: "/img/nebula.jpg"

# --- Footer --- #

author:
  name: Fawad Khan

# --- Social --- #
social-network-links:
  email: "fawadmsee20@gmail.com"
  github: fawadmsee20
  linkedin: "your-linkedin-username"

# --- Share --- #
share-links-active:
  twitter: false
  facebook: false
  linkedin: true

url-pretty: "fawadmsee20.github.io"

# --- Technical --- #

timezone: "Asia/Seoul"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
      social-share: false
  -
    scope:
      path: ""
    values:
      layout: "page"
      show-avatar: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
